### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/vertical-isp#11]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] contract_isp_automatic_invoicing
- [ ] contract_isp_invoice
- [ ] contract_isp_package_configurator
- [ ] contract_isp
- [ ] product_dependencies

**Comment by JayVora-SerpentCS** [comment]
wip!
