### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/vertical-isp#18]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] contract_isp
- [ ] contract_isp_automatic_invoicing
- [ ] contract_isp_invoice
- [ ] contract_isp_package_configurator
- [ ] product_dependencies

**Comment by kamnet** [comment]
How works? Do you have a demo?

**Comment by davinci41** [comment]
How works? Do you have a demo?
