### ISSUE TITLE
Migration to version 8

### ISSUE THREAD

**Issue by max3903** [OCA/vertical-isp#2]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-8
# Modules to migrate
- [ ] contract_isp by @JayVora-SerpentCS 
- [ ] contract_isp_automatic_invoicing by @JayVora-SerpentCS 
- [ ] contract_isp_invoice by @JayVora-SerpentCS 
- [ ] contract_isp_package_configurator by @JayVora-SerpentCS 
- [ ] product_dependencies by @JayVora-SerpentCS

**Comment by bwrsandman** [comment]
Add to the list:
- [ ] Add 8.0 branch from 7.0
- [ ] Move all modules to `__unported__/`
- [ ] Edit .travis.yml and README.md to have the proper branch number
- [ ] Make 8.0 default branch
- [ ] Remove master branch

**Comment by bwrsandman** [comment]
Done what I can for the 8.0 branch, the README.md may need to be expanded.
